### ISSUE TITLE
CAD files

### ISSUE THREAD

**Issue by mbgroot** [Annex-Engineering/Sherpa_Micro-Extruder#1]
Hello.
Will the step files be available?

**Comment by Kirinkunhime** [comment]
When it's released (as in: R1 drops), the CAD might come available.

Here is the relevant part of our 'release standards' taken from our Discord:

* Releases on github will be flagged as alpha, beta, etc. Feel free to test them, a edrawings model will be provided for all alpha models, as will STLs. Not all releases will get a full cad package release. 
* Pretty much all projects will be public facing, you can jump in at any time. Just be aware, you may be throwing parts away if you decide to build. So only jump in when you feel comfortable.
* "CAD" will not be available until there is a release flag on github, no "CAD" will be shared while a project is in alpha or beta.
